#include <iostream>
#include <fstream>
#include <sstream>

#include <algorithm>
#include <iterator>
#include <math.h>

#include <set>
#include <map>
#include <vector>

using namespace std;


template<typename T>
string toString(const T x){ostringstream ss; ss << x; return ss.str();};

unsigned long toUnsignedLong(const char* s){unsigned long ret;istringstream is(s);is >> ret;return ret;};



bool compute_SA(const string gsufsortTool, const string inputTextFile, const string tmp_SA_File, string tmpFolder, unsigned long& n, unsigned long*& SA){
    // a. Compute SA using gsufsort tool
    system(("\""+gsufsortTool+"\" \""+inputTextFile+"\"  --sa  --verbose --output "+tmpFolder).c_str());
    system(("\""+gsufsortTool+"\" \""+inputTextFile+"\"  --sa  --load --print > \""+tmp_SA_File+"\" ").c_str());

    // b. load SA generated by gsufsort tool (it has 4 header rows and then data rows)
    // b.1. read header
    ifstream is_SA(tmp_SA_File.c_str());
    string toRemove;
    // 1st line (header)
    getline(is_SA,toRemove);
    // 2nd line (header with the value of n)
    getline(is_SA,toRemove,'=');
    is_SA >> n; // read value of n 
    getline(is_SA,toRemove);
    // 3th line (header)
    getline(is_SA,toRemove);
    // 4th line (header)
    getline(is_SA,toRemove);

    //b.2. SA memory allocation
    SA  = (unsigned long *) malloc((unsigned long)n * sizeof(unsigned long));
  
    //b.3. load SA from tmp file to memory
    for(unsigned long iLine=0;iLine<n;iLine++){
        unsigned long i, isa;
        is_SA >> i;    // SA index
        is_SA >> isa;  // pointer to the original seq
        SA[i]=isa;
    }

    return true;
}

bool loadOriginalText(const string inputTextFile, const unsigned long n, unsigned char*& T, unsigned long*& idT){
    //load T        (original concatenated text)
    //generates idT (assigns an unique id for each protein)
    
    //a. memory allocation
    T   = (unsigned char *) malloc((unsigned long)n * sizeof(unsigned char));
    idT = (unsigned long *) malloc((unsigned long)n * sizeof(unsigned long));

    //b. id initialization
    unsigned long id=1; // (Important: assigns 0 to the concatenation character)   
    
    // c. from tmp file to memory
    ifstream isT(inputTextFile.c_str());
    for(unsigned long i=0;i<(n-1);i++){
        char c;
        isT >> c;
        T[i]=c;
        // Assign id
        if( (c!='+') && (c!='|')) idT[i]=id;
        else{
            // c is the concatenation character
            // (assigns id=0 to the concatenation character)
            idT[i]=0;
            id++;
        }
    }
    T[n-1]='$'; // added from SA construction
    idT[n-1]=0; // (assigns id=0 to the terminator character)

    return true;
}


bool compute_LCP(const unsigned long n, const unsigned char* T, const unsigned long* SA, unsigned int*& LCP){
    // naive LCP computation
    // requires SA previously computed
    
    // a. memory allocation
    LCP = (unsigned int *) malloc((unsigned long)n * sizeof(unsigned int));
    if(LCP == NULL) {
        fprintf(stderr, "Class mers->computeLCP: Cannot allocate memory.\n");
        exit(EXIT_FAILURE);
    }

    // b. LCP computation from SA data
    for (unsigned long iSA = 1; iSA < n; ++iSA) {
        unsigned int l = 0;
        while ((T[SA[iSA]+l]==T[SA[iSA-1]+l]) &&  T[SA[iSA]+l]!='+') ++l;
        LCP[iSA] = l;
    }

    // c. In order to avoid border cases in repeat classification (in other function), we assign LCP[0]=0
    LCP[0]=0;

    return true;
}

unsigned int numberOfaffectedProteins(const unsigned long i, unsigned long j, const unsigned long* SA, const unsigned long* idT){
    // compute how many proteins have the pattern
    
    // a. ids of proteins that have the pattern
    set<unsigned int> affectedProteins;
    // b. for each pattern occurrence, takes its protein id
    for(unsigned long iSA=i;iSA<=j;iSA++){
        // It finds the pattern proteinID
        unsigned long pID=(idT[SA[iSA]]);
        // Add proteinID
        affectedProteins.insert(pID);
    }

    return affectedProteins.size();

}


void AddPatternIfApplicable(std::ofstream& os, const unsigned long i, const unsigned long j, const unsigned int minNumberOfAffectedSequences, const unsigned long* SA, const unsigned long* idT, const string & pattern){
    // save pattern to file if the pattern satisfy required conditions (the numberOfaffectedProteins)
    // a. compute the numberOfaffectedProteins
    unsigned long affectedProteins = numberOfaffectedProteins(i,j,SA,idT);
    // b. if the pattern satisfy the condition, save it to the file
    if(affectedProteins>=minNumberOfAffectedSequences){
             os << pattern;                  // pattern
	     os << "," << pattern.size();    // length of pattern
	     os << "," << (j-i+1);           // instances 
	     os << "," << affectedProteins;  // affected proteins
	     os << endl; 
    }
    
}


void addOccurrence(map<char, unsigned long> &map1, char e){
    // Symbol dictionary <symbol, instances>
    if(map1.find(e) != map1.end()){
        // a. add 1 instance
        // The concatenation separator ('+') has a particular treatment.
        // The separator can only have a unique instance, because it represent different separator symbols (e.g. $_1,$_2,...).
        if(e!='+') map1[e]++;  
    }    
    else{
        // b. add the first time to the dictionary
        map1.insert(map<char,unsigned long>::value_type(e,1));
    }
}


void computeTailleferPattern(const unsigned int l, const unsigned long i, unsigned long j, const unsigned long n, const unsigned int minNumberOfAffectedSequences, const unsigned char* T, const unsigned long* idT, const unsigned long* SA, const unsigned int* LCP, std::ofstream& osSMR, std::ofstream& osNN, std::ofstream& osNE){
    // pattern classification 
    // require SA, LCP, l-interval (l,i,j)
    
    // a. get the pattern
    string pattern="";
    for(unsigned int isuff=0;isuff<l;isuff++) pattern+=(T[SA[i]+isuff]); 
    
    // b. check if the pattern is a Maximal Repeat (MR)
    char sigma = T[SA[i]-1];   // Any pattern left context to next
                               // check if they are all the same. 
                               // If they are all the same, then 
                               // it's not a MR 
                               
    bool is_MR = (sigma=='+'); // is_MR flag inicialization.
                               // If sigma is a separator then it's a MR

    // Survey of left & right context
    map<char, unsigned long> LCTT, RCTT; // empty dictionaries
    for(unsigned long k=i;k<=j;k++){
        char sigma_l=T[SA[k]-1]; // left  context
        char sigma_r=T[SA[k]+l]; // right context
        addOccurrence(LCTT, sigma_l);
        addOccurrence(RCTT, sigma_r);
        // l-interval always contains at least one element 
        // that is not right extensible (by definition)
        // We only need to check if it's not left-extensible
        if(sigma!=sigma_l) 
            is_MR = true; // It's not left-extensible then it is a MR
    }

    // b. If the pattern is MR then classify it.
    if(is_MR){  // Is it SMR, NN or NE?
        // MR is a SMR?
        // There is not pair of occurrences that has the same left or right-context
        // Then, they cant't be extended
        bool cantBeExtended = true;
        for ( std::map<char,unsigned long>::iterator it = LCTT.begin(); it != LCTT.end() && cantBeExtended; ++it){
            cantBeExtended = (cantBeExtended && (it->second<=1));
        }
        for ( std::map<char,unsigned long>::iterator it = RCTT.begin(); it != RCTT.end() && cantBeExtended; ++it){
            cantBeExtended = (cantBeExtended && (it->second<=1));
        }

        if(cantBeExtended) {
                AddPatternIfApplicable(osSMR, i, j, minNumberOfAffectedSequences, SA, idT, pattern); // It is SMR;
        }
        else{   // Is it NN or NE?
            // Find an occurrence that is not right and left extensible
            // If it exist then it is a NN
            bool isNested = true;
            for(unsigned long k=i;(k<=j) && isNested;k++){ // For each occurence ...
                char sigma_l=T[SA[k]-1];
                char sigma_r=T[SA[k]+l];
                if( (LCTT[sigma_l]<=1) && (RCTT[sigma_r]<=1) ){
                    // This occurence is not right and left extensible
                    isNested = false;
                }
            }
            if(isNested) { 
                AddPatternIfApplicable(osNE, i, j, minNumberOfAffectedSequences, SA, idT, pattern); // It is a NE
                                                                                        // (all pattern occurrence are nested)
            }
            else         { 
                AddPatternIfApplicable(osNN, i, j, minNumberOfAffectedSequences, SA, idT, pattern); // It is a NN
                                                                                        // (At least one pattern occurrence is non-nested)
            }
        }
    } 
}

void addHeader(std::ofstream& os){
    // output files header
    os << "Pattern,PatternLength,Instances,AffectedProteins" << endl;
}

bool computePatterns(const string outputFilename, const unsigned long n, const unsigned char* T, const unsigned long* idT, const unsigned long* SA, const unsigned int* LCP, const unsigned int minLengthOfPattern, const unsigned int maxLengthOfPattern, const unsigned int minNumberOfAffectedSequences){

    // a. Output files initialization
    // ... SMR
    ofstream osSMR((outputFilename+"_SMR.csv").c_str());
    if(!osSMR.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open SMR file" << endl;
        return false;
    }
    addHeader(osSMR);
    // ... NN
    ofstream osNN((outputFilename+"_NN.csv").c_str());
    if(!osNN.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open NN file" << endl;
        return false;
    }
    addHeader(osNN);
    // ... NE
    ofstream osNE((outputFilename+"_NE.csv").c_str());
    if(!osSMR.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open NE file" << endl;
        return false;
    }
    addHeader(osNE);
    
    // b. Patterns classification. 
    // ... Compute Intervals of the potential MRs
    vector<unsigned int> interval_l;
    vector<unsigned long> interval_i;
    vector<unsigned long> interval_j;
    
    interval_l.push_back(0);
    interval_i.push_back(0);
    interval_j.push_back(0); // NULL
    for(unsigned long i=1;i<=n;i++){
        unsigned long lb = i - 1;
        
        while (LCP[i] < interval_l[interval_l.size()-1]){
            interval_j[interval_j.size()-1]=i-1;
           
	    // l-interval reported, then its analyzed: ¿is a MR?
            unsigned int  l = interval_l[interval_l.size()-1];
            unsigned long i = interval_i[interval_i.size()-1];
            unsigned long j = interval_j[interval_j.size()-1];
            if((l>=minLengthOfPattern) && (l<=maxLengthOfPattern)){ 
                // compute pattern. If it is MR AND satisfy additional conditions then save it to the corresponding output file
                computeTailleferPattern(l,i,j,n,minNumberOfAffectedSequences,T,idT,SA,LCP,osSMR, osNN, osNE);
            }
            
            lb = interval_i[interval_i.size()-1];
            interval_l.pop_back();
            interval_i.pop_back();
            interval_j.pop_back();
            
        }
        if(LCP[i] > interval_l[interval_l.size()-1]){
            interval_l.push_back(LCP[i]);
            interval_i.push_back(lb);
            interval_j.push_back(0); // NULL
        }
    }

    // c. Close files
    osSMR.close();
    osNN.close();
    osNE.close();

    return true;
}



int main(int argc, const char *argv[]) {
   
  // paramaeter checking
    if(argc!=6){
                cout<<"usage example: " << argv[0] << " inputFolder minLengthOfPattern maxLengthOfPattern minNumberOfAffectedSequences prefixOfOutputFilename" << endl;
                return 0;
    }


    bool ok;




    // 1. Parameters
    // =============
    //a. inputFolder (folder with *.fasta files)
    string inputFolder=  argv[1];

    //b. minLengthOfPattern
    unsigned long minLengthOfPattern=toUnsignedLong(argv[2]);
    
    //c. maxLengthOfPattern
    unsigned long maxLengthOfPattern=toUnsignedLong(argv[3]);
    
    //d. minNumberOfAffectedSequences
    unsigned long minNumberOfAffectedSequences=toUnsignedLong(argv[4]);
    
    //e. prefix of output file
    string prefixOfOutputFilename  =  argv[5];


    // More Parameters
    // ... folder for tmp files generated by this program
    string tmpFolder = "./tmp/"; 
    // ... python script that transform seqs from *.fasta to (ABCD+AJHJHGD+...+KJHKAJSH+$) ('+' is the character separator)
    // ... requires biopython previously installed
    string multifastaConcatenateTool = "./multifastaConcatenate.py";
    // ... temporal output file name of multifastaConcatenateTool
    string tmpFastaConcatenatedFiles = tmpFolder+"_inputConcatenatedFastaFiles.txt";
    // ... tool that compute Suffix Array (SA) (uses 64 bits)
    // ... requieres gsufsort-64 previously installed
    // ... Instructions to install gsufsort-64
    // ... a. git clone https://github.com/felipelouza/gsufsort.git
    // ... b. cd gsufsort
    // ... c. make
    string gsufsortTool ="./gsufsort/gsufsort-64";
    // ... temporal output file name of SA from gsufsortTool
    string tmp_SA_File=tmpFolder+"_SA.tmp";
    
        
    // Variables
    unsigned char *T;   // concatenated seqs
    unsigned long *idT; // seq id for each letter from concatenated seqs
    unsigned long *SA;  // SA 
    unsigned int *LCP;  // LCP
    unsigned long n;    // size of T

    set<string> SMR;    // Super      Maximal Repeats
    set<string> NN;     // Non-Nested Maximal Repeats
    set<string> NE;     // Nested     Maximal Repeats
    
    
    // 0. tmp folder creation
    system(("mkdir -p "+tmpFolder).c_str());    
    
    // 1. Generates inputfile T (ABCD+DJHGAJHJHGD+...+KJHKAJSHKJASH+)
    system(("python3 "+multifastaConcatenateTool+" "+inputFolder+" "+tmpFastaConcatenatedFiles).c_str());    
    cout << "Phase 1: Fasta files Concatenation                -> Finished! " << endl;

    // 2. Compute SA and n. 
    ok=compute_SA(gsufsortTool, tmpFastaConcatenatedFiles, tmp_SA_File, tmpFolder,n, SA);
    if(!ok) {
        cout << "Error: compute_SA!" << endl;
        return false;
    }
    cout << "Phase 2: Compute SA                               -> Finished! " << endl;
    
    
    // 3. Load original text (T). I did it after SA in order to have more memory for SA computation.
    ok=loadOriginalText(tmpFastaConcatenatedFiles, n, T, idT);
    cout << "Phase 3: Load in memory conatenated *.fasta files -> Finished! " << endl;
    
    // 4. Compute LCP. 
    ok=compute_LCP(n, T, SA, LCP);
    if(!ok) return 1;
    cout << "Phase 4: Compute LCP                              -> Finished! " << endl;
 
 
    // 5. patterns computation
    string composedPrefixName=prefixOfOutputFilename;
    composedPrefixName+="_"+toString(minLengthOfPattern);
    composedPrefixName+="_"+toString(maxLengthOfPattern);
    composedPrefixName+="_"+toString(minNumberOfAffectedSequences);
    
    ok = computePatterns(composedPrefixName, n, T, idT, SA, LCP, minLengthOfPattern, maxLengthOfPattern, minNumberOfAffectedSequences);
    if(!ok) return 1;
    cout << "Phase 5: Compute patterns                         -> Finished! " << endl;

    
  
    return 0;

  
}


