#include <iostream>
#include <fstream>
#include <sstream>

#include <algorithm>
#include <iterator>
#include <math.h>
#include <ctime>
#include <cstring>

#include <set>
#include <map>
#include <vector>
#include <string>
#include <utility>

using namespace std;


template<typename T>
string toString(const T x){ostringstream ss; ss << x; return ss.str();};

unsigned long toUnsignedLong(const char* s){unsigned long ret;istringstream is(s);is >> ret;return ret;};



bool compute_SA(const string gsufsortTool, const string inputTextFile, const string tmp_SA_File, string tmpFolder, unsigned long& n, unsigned long*& SA){
    // a. Compute SA using gsufsort tool
    system(("\""+gsufsortTool+"\" \""+inputTextFile+"\"  --sa  --verbose --output "+tmpFolder).c_str());
    system(("\""+gsufsortTool+"\" \""+inputTextFile+"\"  --sa  --load --print > \""+tmp_SA_File+"\" ").c_str());

    // b. load SA generated by gsufsort tool (it has 4 header rows and then data rows)
    // b.1. read header
    ifstream is_SA(tmp_SA_File.c_str());
    string toRemove;
    // 1st line (header)
    getline(is_SA,toRemove);
    // 2nd line (header with the value of n)
    getline(is_SA,toRemove,'=');
    is_SA >> n; // read value of n 
    getline(is_SA,toRemove);
    // 3th line (header)
    getline(is_SA,toRemove);
    // 4th line (header)
    getline(is_SA,toRemove);

    //b.2. SA memory allocation
    SA  = (unsigned long *) malloc((unsigned long)n * sizeof(unsigned long));
  
    //b.3. load SA from tmp file to memory
    for(unsigned long iLine=0;iLine<n;iLine++){
        unsigned long i, isa;
        is_SA >> i;    // SA index
        is_SA >> isa;  // pointer to the original seq
        SA[i]=isa;
    }

    return true;
}

bool loadOriginalText(const string inputTextFile, const unsigned long n, unsigned char*& T, unsigned long*& idT){
    //load T        (original concatenated text)
    //generates idT (assigns an unique id for each protein)
    
    //a. memory allocation
    T   = (unsigned char *) malloc((unsigned long)n * sizeof(unsigned char));
    idT = (unsigned long *) malloc((unsigned long)n * sizeof(unsigned long));

    //b. id initialization
    unsigned long id=1; // (Important: assigns 0 to the concatenation character)   
    
    // c. from tmp file to memory
    ifstream isT(inputTextFile.c_str());
    for(unsigned long i=0;i<(n-1);i++){
        char c;
        isT >> c;
        T[i]=c;
        // Assign id
        if( (c!='+') && (c!='|')) idT[i]=id;
        else{
            // c is the concatenation character
            // (assigns id=0 to the concatenation character)
            idT[i]=0;
            id++;
        }
    }
    T[n-1]='$'; // added from SA construction
    idT[n-1]=0; // (assigns id=0 to the terminator character)

    return true;
}


bool compute_LCP_naive(const unsigned long n, const unsigned char* T, const unsigned long* SA, unsigned int*& LCP){
    // naive LCP computation (O(n²) time complexity)
    // requires SA previously computed
    
    // a. memory allocation
    LCP = (unsigned int *) malloc((unsigned long)n * sizeof(unsigned int));
    if(LCP == NULL) {
        fprintf(stderr, "Class mers->computeLCP: Cannot allocate memory.\n");
        exit(EXIT_FAILURE);
    }

    // b. LCP computation from SA data
    for (unsigned long iSA = 1; iSA < n; ++iSA) {
        unsigned int l = 0;
        while ((T[SA[iSA]+l]==T[SA[iSA-1]+l]) &&  T[SA[iSA]+l]!='+') ++l;
        LCP[iSA] = l;
    }

    // c. In order to avoid border cases in repeat classification (in other function), we assign LCP[0]=0
    LCP[0]=0;

    return true;
}

bool compute_LCP_kasai(const unsigned long n, const unsigned char* T, const unsigned long* SA, unsigned int*& LCP){
    // Kasai's algorithm for LCP computation (O(n) time complexity)
    // requires SA previously computed
    
    // a. memory allocation
    LCP = (unsigned int *) malloc((unsigned long)n * sizeof(unsigned int));
    if(LCP == NULL) {
        fprintf(stderr, "Class mers->computeLCP_kasai: Cannot allocate memory.\n");
        exit(EXIT_FAILURE);
    }

    // b. Build rank array (inverse of SA): rank[SA[i]] = i
    unsigned long* rank = (unsigned long *) malloc((unsigned long)n * sizeof(unsigned long));
    if(rank == NULL) {
        fprintf(stderr, "Class mers->computeLCP_kasai: Cannot allocate memory for rank array.\n");
        exit(EXIT_FAILURE);
    }
    
    for (unsigned long i = 0; i < n; i++) {
        rank[SA[i]] = i;
    }

    // c. Initialize LCP[0] = 0
    LCP[0] = 0;

    // d. Process suffixes in original text order (not SA order)
    // Key insight: LCP[rank[i]] >= LCP[rank[i-1]] - 1
    unsigned int h = 0;
    for (unsigned long i = 0; i < n; i++) {
        if (rank[i] > 0) {
            unsigned long j = SA[rank[i] - 1];
            // Skip already matched characters using the property above
            while ((i + h < n) && (j + h < n) && 
                   (T[i + h] == T[j + h]) && 
                   (T[i + h] != '+')) {
                h++;
            }
            LCP[rank[i]] = h;
            // Key optimization: LCP[rank[i+1]] >= h-1, so we can start from h-1 next time
            if (h > 0) h--;
        }
    }

    free(rank);
    return true;
}

bool compute_LCP(const unsigned long n, const unsigned char* T, const unsigned long* SA, unsigned int*& LCP, const string& algorithm = "naive"){
    // Wrapper function that dispatches to the selected LCP algorithm
    if (algorithm == "kasai") {
        return compute_LCP_kasai(n, T, SA, LCP);
    } else if (algorithm == "naive") {
        return compute_LCP_naive(n, T, SA, LCP);
    } else {
        fprintf(stderr, "Error: Unknown LCP algorithm '%s'. Use 'naive' or 'kasai'.\n", algorithm.c_str());
        return false;
    }
}

std::map<unsigned long, std::vector<unsigned long>> getAffectedProteins(const unsigned long i, unsigned long j, const unsigned char* T, const unsigned long* SA, const unsigned long* idT){
    // compute how many proteins have the pattern
    
    // a. map of protein ids with local starting index list
    std::map<unsigned long, std::vector<unsigned long>> affectedProteins;
    // b. for each pattern occurrence, takes its protein id
    for(unsigned long iSA=i;iSA<=j;iSA++){
        // suffix array has index of pattern start in T
        unsigned long iT = SA[iSA];
        // that same index in idT provides proteinID
        unsigned long pID=(idT[iT]);
        // to get local index of pattern in local protein string
        // we need to offset iT to the leftmost "+" separator index
        unsigned long jT = iT;
        while(jT > 0){
            if(T[jT-1] != '+'){
                jT--;
            }else{
                break;
            }
        }
        iT -= jT;

        // Add proteinID and starting position of pattern
        std::map<unsigned long, std::vector<unsigned long>>::iterator it = affectedProteins.find(pID);
        if (it != affectedProteins.end()) {
            it->second.push_back(iT);
        } else {
            affectedProteins[pID] = {iT};
        }
    }

    return affectedProteins;

}

std::set<unsigned long> getMapKeys(std::map<unsigned long, std::vector<unsigned long>> map){
    std::set<unsigned long> keySet;

    for (const auto& pair : map) {
        keySet.insert(pair.first);
    }
    return keySet;
}

void AddPatternIfApplicable(std::ofstream& os, const unsigned long i, const unsigned long j, const unsigned int minNumberOfAffectedSequences, const unsigned char* T, const unsigned long* SA, const unsigned long* idT, const string & pattern, const unsigned long patternId, const string patternType, std::ofstream& osALL, std::ofstream& osPOS){
    // save pattern to file if the pattern satisfy required conditions (the numberOfaffectedProteins)
    // a. compute the numberOfaffectedProteins
    std::map<unsigned long, std::vector<unsigned long>> affectedProteins = getAffectedProteins(i,j,T,SA,idT);
    set<unsigned long> affectedProteinIds = getMapKeys(affectedProteins);
    unsigned long numberOfAffectedProteins = affectedProteinIds.size();
    // b. if the pattern satisfy the condition, save it to the file
    if(numberOfAffectedProteins>=minNumberOfAffectedSequences){
        // 1. add to corresponding pattern type csv output
        /*os << pattern;                  // pattern
	    os << "," << pattern.size();    // length of pattern
	    os << "," << (j-i+1);           // instances 
	    os << "," << numberOfAffectedProteins;  // affected proteins
	    os << endl; */

        // 2. add to global pattern dataset csv output
        osALL << patternId << ",";
        osALL << patternType << ",";
        osALL << pattern << ",";
        //osALL << "\"length\":" << pattern.size() << ",";
        osALL << (j-i+1) << endl;
        
        for (std::set<unsigned long>::iterator it = affectedProteinIds.begin(); it != affectedProteinIds.end(); ++it) {
            std::vector<unsigned long> positions = affectedProteins.find(*it)->second;
            for (std::vector<unsigned long>::iterator pit = positions.begin(); pit != positions.end(); ++pit) {
                osPOS << patternId << ",";
                //offset because idT starts counting at 1
                osPOS << (*it)-1 << ",";
                osPOS << *pit << endl;
            }
        }
    }
}


void addOccurrence(map<char, unsigned long> &map1, char e){
    // Symbol dictionary <symbol, instances>
    if(map1.find(e) != map1.end()){
        // a. add 1 instance
        // The concatenation separator ('+') has a particular treatment.
        // The separator can only have a unique instance, because it represent different separator symbols (e.g. $_1,$_2,...).
        if(e!='+') map1[e]++;  
    }    
    else{
        // b. add the first time to the dictionary
        map1.insert(map<char,unsigned long>::value_type(e,1));
    }
}


void computeTailleferPattern(const unsigned int l, const unsigned long i, unsigned long j, const unsigned long n, const unsigned int minNumberOfAffectedSequences, const unsigned char* T, const unsigned long* idT, const unsigned long* SA, const unsigned int* LCP, unsigned long &patternId, std::ofstream& osSMR, std::ofstream& osNN, std::ofstream& osNE, std::ofstream& osALL, std::ofstream& osPOS){
    // pattern classification 
    // require SA, LCP, l-interval (l,i,j)
    
    // a. get the pattern
    string pattern="";
    for(unsigned int isuff=0;isuff<l;isuff++) pattern+=(T[SA[i]+isuff]); 
    
    // b. check if the pattern is a Maximal Repeat (MR)
    char sigma = T[SA[i]-1];   // Any pattern left context to next
                               // check if they are all the same. 
                               // If they are all the same, then 
                               // it's not a MR 
                               
    bool is_MR = (sigma=='+'); // is_MR flag inicialization.
                               // If sigma is a separator then it's a MR

    // Survey of left & right context
    map<char, unsigned long> LCTT, RCTT; // empty dictionaries
    for(unsigned long k=i;k<=j;k++){
        char sigma_l=T[SA[k]-1]; // left  context
        char sigma_r=T[SA[k]+l]; // right context
        addOccurrence(LCTT, sigma_l);
        addOccurrence(RCTT, sigma_r);
        // l-interval always contains at least one element 
        // that is not right extensible (by definition)
        // We only need to check if it's not left-extensible
        if(sigma!=sigma_l) 
            is_MR = true; // It's not left-extensible then it is a MR
    }

    // b. If the pattern is MR then classify it.
    if(is_MR){  // Is it SMR, NN or NE?
        // MR is a SMR?
        // There is not pair of occurrences that has the same left or right-context
        // Then, they cant't be extended
        bool cantBeExtended = true;
        for ( std::map<char,unsigned long>::iterator it = LCTT.begin(); it != LCTT.end() && cantBeExtended; ++it){
            cantBeExtended = (cantBeExtended && (it->second<=1));
        }
        for ( std::map<char,unsigned long>::iterator it = RCTT.begin(); it != RCTT.end() && cantBeExtended; ++it){
            cantBeExtended = (cantBeExtended && (it->second<=1));
        }

        // default pattern type
        string patternType = "MR";
        if(cantBeExtended) {
                patternType = "SMR";
                AddPatternIfApplicable(osSMR, i, j, minNumberOfAffectedSequences, T, SA, idT, pattern, patternId, patternType, osALL, osPOS); // It is SMR;
        }
        else{   // Is it NN or NE?
            // Find an occurrence that is not right and left extensible
            // If it exist then it is a NN
            bool isNested = true;
            for(unsigned long k=i;(k<=j) && isNested;k++){ // For each occurence ...
                char sigma_l=T[SA[k]-1];
                char sigma_r=T[SA[k]+l];
                if( (LCTT[sigma_l]<=1) && (RCTT[sigma_r]<=1) ){
                    // This occurence is not right and left extensible
                    isNested = false;
                }
            }
            if(isNested) {
                patternType = "NE";
                AddPatternIfApplicable(osNE, i, j, minNumberOfAffectedSequences, T, SA, idT, pattern, patternId, patternType, osALL, osPOS); // It is a NE
                                                                                        // (all pattern occurrence are nested)
            }
            else { 
                patternType = "NN";
                AddPatternIfApplicable(osNN, i, j, minNumberOfAffectedSequences, T, SA, idT, pattern, patternId, patternType, osALL, osPOS); // It is a NN
                                                                                        // (At least one pattern occurrence is non-nested)
            }
        }
        patternId++;
    } 
}

void addHeader(std::ofstream& os){
    // output files header
    os << "Pattern,PatternLength,Instances,AffectedProteins" << endl;
}

bool computePatterns(const string outputFilename, const unsigned long n, const unsigned char* T, const unsigned long* idT, const unsigned long* SA, const unsigned int* LCP, const unsigned int minLengthOfPattern, const unsigned int maxLengthOfPattern, const unsigned int minNumberOfAffectedSequences){

    // a. Output files initialization
    // ... SMR
    ofstream osSMR((outputFilename+"_SMR.csv").c_str());
    if(!osSMR.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open SMR file" << endl;
        return false;
    }
    addHeader(osSMR);
    // ... NN
    ofstream osNN((outputFilename+"_NN.csv").c_str());
    if(!osNN.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open NN file" << endl;
        return false;
    }
    addHeader(osNN);
    // ... NE
    ofstream osNE((outputFilename+"_NE.csv").c_str());
    if(!osSMR.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open NE file" << endl;
        return false;
    }
    addHeader(osNE);

    // ... unified MR dataset
    ofstream osALL((outputFilename+"_PATTERNS.csv").c_str());
    if(!osALL.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open ALL file" << endl;
        return false;
    }
    osALL << "pattern_id,type,pattern,instances" << endl;

    // ... unified MR dataset
    ofstream osPOS((outputFilename+"_POSITIONS.csv").c_str());
    if(!osPOS.good()){
        cout << "Error! function " << __FUNCTION__ << " cannot open ALL file" << endl;
        return false;
    }
    osPOS << "pattern_id,protein_id,position" << endl;

    // b. Patterns classification. 
    unsigned long patternId = 0;
    // ... Compute Intervals of the potential MRs
    vector<unsigned int> interval_l;
    vector<unsigned long> interval_i;
    vector<unsigned long> interval_j;
    
    interval_l.push_back(0);
    interval_i.push_back(0);
    interval_j.push_back(0); // NULL
    for(unsigned long i=1;i<=n;i++){
        unsigned long lb = i - 1;
        
        while (LCP[i] < interval_l[interval_l.size()-1]){
            interval_j[interval_j.size()-1]=i-1;
           
	    // l-interval reported, then its analyzed: ¿is a MR?
            unsigned int  l = interval_l[interval_l.size()-1];
            unsigned long i = interval_i[interval_i.size()-1];
            unsigned long j = interval_j[interval_j.size()-1];
            if((l>=minLengthOfPattern) && (l<=maxLengthOfPattern)){ 
                // compute pattern. If it is MR AND satisfy additional conditions then save it to the corresponding output file
                computeTailleferPattern(l,i,j,n,minNumberOfAffectedSequences,T,idT,SA,LCP,patternId, osSMR, osNN, osNE, osALL, osPOS);
            }
            
            lb = interval_i[interval_i.size()-1];
            interval_l.pop_back();
            interval_i.pop_back();
            interval_j.pop_back();
            
        }
        if(LCP[i] > interval_l[interval_l.size()-1]){
            interval_l.push_back(LCP[i]);
            interval_i.push_back(lb);
            interval_j.push_back(0); // NULL
        }
    }

    // c. Close files
    osSMR.close();
    osNN.close();
    osNE.close();
    osPOS.close();
    osALL.close();

    return true;
}

// Helper function to compare two LCP arrays
bool compareLCPArrays(unsigned int* lcp1, unsigned int* lcp2, unsigned long n) {
    for (unsigned long i = 0; i < n; i++) {
        if (lcp1[i] != lcp2[i]) {
            return false;
        }
    }
    return true;
}

// Helper function to compute checksum of LCP array
unsigned long computeLCPChecksum(unsigned int* lcp, unsigned long n) {
    unsigned long checksum = 0;
    for (unsigned long i = 0; i < n; i++) {
        checksum += lcp[i];
        checksum = (checksum << 1) | (checksum >> 31); // Simple hash
    }
    return checksum;
}

// Helper function to print LCP array differences
void printLCPDiff(unsigned int* lcp1, unsigned int* lcp2, unsigned long n, const unsigned long* SA, const unsigned char* T) {
    cout << "LCP Array Differences:" << endl;
    bool foundDiff = false;
    for (unsigned long i = 0; i < n; i++) {
        if (lcp1[i] != lcp2[i]) {
            foundDiff = true;
            cout << "  Index " << i << ": naive=" << lcp1[i] << ", kasai=" << lcp2[i];
            if (i > 0 && SA != NULL && T != NULL) {
                cout << " (SA[" << i-1 << "]=" << SA[i-1] << ", SA[" << i << "]=" << SA[i] << ")";
            }
            cout << endl;
        }
    }
    if (!foundDiff) {
        cout << "  No differences found." << endl;
    }
}

// Test case runner
bool runTestCase(const string& testName, const string& text, const unsigned long* SA, unsigned long n) {
    cout << "\n=== Test: " << testName << " ===" << endl;
    cout << "Text length: " << n << endl;
    
    // Convert string to unsigned char array
    unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
    for (unsigned long i = 0; i < n; i++) {
        T[i] = (unsigned char)text[i];
    }
    
    // Compute LCP with both algorithms
    unsigned int* lcp_naive = NULL;
    unsigned int* lcp_kasai = NULL;
    
    clock_t start, end;
    
    start = clock();
    bool ok1 = compute_LCP_naive(n, T, SA, lcp_naive);
    end = clock();
    double naive_time = ((double)(end - start)) / CLOCKS_PER_SEC;
    
    start = clock();
    bool ok2 = compute_LCP_kasai(n, T, SA, lcp_kasai);
    end = clock();
    double kasai_time = ((double)(end - start)) / CLOCKS_PER_SEC;
    
    if (!ok1 || !ok2) {
        cout << "ERROR: Failed to compute LCP arrays" << endl;
        free(T);
        if (lcp_naive) free(lcp_naive);
        if (lcp_kasai) free(lcp_kasai);
        return false;
    }
    
    // Compare results
    bool match = compareLCPArrays(lcp_naive, lcp_kasai, n);
    unsigned long checksum_naive = computeLCPChecksum(lcp_naive, n);
    unsigned long checksum_kasai = computeLCPChecksum(lcp_kasai, n);
    
    cout << "Naive time: " << naive_time << "s" << endl;
    cout << "Kasai time: " << kasai_time << "s" << endl;
    cout << "Speedup: " << (naive_time > 0 ? naive_time / kasai_time : 0) << "x" << endl;
    cout << "Checksum (naive): " << checksum_naive << endl;
    cout << "Checksum (kasai): " << checksum_kasai << endl;
    
    if (!match) {
        cout << "FAILED: LCP arrays do not match!" << endl;
        printLCPDiff(lcp_naive, lcp_kasai, n, SA, T);
    } else {
        cout << "PASSED: LCP arrays match perfectly" << endl;
    }
    
    free(T);
    free(lcp_naive);
    free(lcp_kasai);
    
    return match;
}

// Simple SA computation for testing (naive approach)
void computeSA_naive(const unsigned char* T, unsigned long n, unsigned long* SA) {
    // Create array of indices
    vector<pair<string, unsigned long>> suffixes;
    for (unsigned long i = 0; i < n; i++) {
        string suffix = "";
        for (unsigned long j = i; j < n; j++) {
            suffix += (char)T[j];
        }
        suffixes.push_back(make_pair(suffix, i));
    }
    
    // Sort by suffix string
    sort(suffixes.begin(), suffixes.end());
    
    // Fill SA array
    for (unsigned long i = 0; i < n; i++) {
        SA[i] = suffixes[i].second;
    }
}

// Integrated test function
bool runLCPComparisonTests() {
    cout << "========================================" << endl;
    cout << "LCP Algorithm Comparison Tests" << endl;
    cout << "========================================" << endl;
    
    int passed = 0;
    int total = 0;
    
    // Test Case 1: Simple string without separators
    {
        string text = "banana$";
        unsigned long n = text.length();
        unsigned long* SA = (unsigned long*)malloc(n * sizeof(unsigned long));
        unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
        for (unsigned long i = 0; i < n; i++) {
            T[i] = (unsigned char)text[i];
        }
        computeSA_naive(T, n, SA);
        total++;
        if (runTestCase("Simple string (banana)", text, SA, n)) {
            passed++;
        }
        free(SA);
        free(T);
    }
    
    // Test Case 2: String with separators (protein-like)
    {
        string text = "ABCD+EFAB+GHAB+$";
        unsigned long n = text.length();
        unsigned long* SA = (unsigned long*)malloc(n * sizeof(unsigned long));
        unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
        for (unsigned long i = 0; i < n; i++) {
            T[i] = (unsigned char)text[i];
        }
        computeSA_naive(T, n, SA);
        total++;
        if (runTestCase("String with separators", text, SA, n)) {
            passed++;
        }
        free(SA);
        free(T);
    }
    
    // Test Case 3: Repeated patterns
    {
        string text = "AAAA+BBBB+AAAA+$";
        unsigned long n = text.length();
        unsigned long* SA = (unsigned long*)malloc(n * sizeof(unsigned long));
        unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
        for (unsigned long i = 0; i < n; i++) {
            T[i] = (unsigned char)text[i];
        }
        computeSA_naive(T, n, SA);
        total++;
        if (runTestCase("Repeated patterns", text, SA, n)) {
            passed++;
        }
        free(SA);
        free(T);
    }
    
    // Test Case 4: Single character
    {
        string text = "A$";
        unsigned long n = text.length();
        unsigned long* SA = (unsigned long*)malloc(n * sizeof(unsigned long));
        unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
        for (unsigned long i = 0; i < n; i++) {
            T[i] = (unsigned char)text[i];
        }
        computeSA_naive(T, n, SA);
        total++;
        if (runTestCase("Single character", text, SA, n)) {
            passed++;
        }
        free(SA);
        free(T);
    }
    
    // Test Case 5: All same characters
    {
        string text = "AAAAA$";
        unsigned long n = text.length();
        unsigned long* SA = (unsigned long*)malloc(n * sizeof(unsigned long));
        unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
        for (unsigned long i = 0; i < n; i++) {
            T[i] = (unsigned char)text[i];
        }
        computeSA_naive(T, n, SA);
        total++;
        if (runTestCase("All same characters", text, SA, n)) {
            passed++;
        }
        free(SA);
        free(T);
    }
    
    // Test Case 6: Protein-like sequence
    {
        string text = "MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEKAVQVKVKALPDAQFEVVHSLAKWKRQTLGQHDFSAGEGLYTHMKALRPDEDRLSPLHSVYVDQWDWERVMGDGERQFSTLKSTVEAIWAGIKATEAAVSEEFGLAPFLPDQIHFVHSQELLSRYPDLDAKGRERAIAKDLGAVFLVGIGGKLSDGHRHDVRAPDYDDWSTPSELGHAGLNGDILVWNPVLEDAFELSSMGIRVDADTLKHQLALTGDEDRLELEWHQALLRGEMPQTIGGGIGQSRLTMLLLQLPHIGQVQAGVWPAAVRESVPSLL$";
        unsigned long n = text.length();
        unsigned long* SA = (unsigned long*)malloc(n * sizeof(unsigned long));
        unsigned char* T = (unsigned char*)malloc(n * sizeof(unsigned char));
        for (unsigned long i = 0; i < n; i++) {
            T[i] = (unsigned char)text[i];
        }
        computeSA_naive(T, n, SA);
        total++;
        if (runTestCase("Protein-like sequence", text, SA, n)) {
            passed++;
        }
        free(SA);
        free(T);
    }
    
    // Summary
    cout << "\n========================================" << endl;
    cout << "Test Summary" << endl;
    cout << "========================================" << endl;
    cout << "Passed: " << passed << "/" << total << endl;
    if (passed == total) {
        cout << "All tests PASSED!" << endl;
        return true;
    } else {
        cout << "Some tests FAILED!" << endl;
        return false;
    }
}

// Forward declarations for test functions
bool runLCPComparisonTests();

int main(int argc, const char *argv[]) {
   
    bool ok;
    
    // Parse command-line flags
    string lcpAlgorithm = "naive"; // default
    bool testMode = false;
    vector<string> positionalArgs;
    
    // Parse arguments (handle flags and positional arguments)
    for (int i = 1; i < argc; i++) {
        string arg = argv[i];
        if (arg == "--lcp-algorithm" || arg == "-L") {
            if (i + 1 < argc) {
                lcpAlgorithm = argv[++i];
                if (lcpAlgorithm != "naive" && lcpAlgorithm != "kasai") {
                    cout << "Error: --lcp-algorithm must be 'naive' or 'kasai'" << endl;
                    return 1;
                }
            } else {
                cout << "Error: --lcp-algorithm requires a value (naive or kasai)" << endl;
                return 1;
            }
        } else if (arg == "--test-lcp" || arg == "-T") {
            testMode = true;
        } else if (arg == "--help" || arg == "-h") {
            cout << "Usage: " << argv[0] << " [OPTIONS] inputParentFolder minLengthOfPattern maxLengthOfPattern minNumberOfAffectedSequences outputFolder proteinGroupFolderName" << endl;
            cout << "\nOptions:" << endl;
            cout << "  --lcp-algorithm, -L <naive|kasai>  Select LCP algorithm (default: naive)" << endl;
            cout << "  --test-lcp, -T                     Run LCP algorithm comparison tests" << endl;
            cout << "  --help, -h                         Show this help message" << endl;
            return 0;
        } else {
            positionalArgs.push_back(arg);
        }
    }
    
    // If test mode, run tests and exit
    if (testMode) {
        cout << "Running LCP algorithm comparison tests..." << endl;
        bool testResult = runLCPComparisonTests();
        return testResult ? 0 : 1;
    }
    
    // parameter checking
    if(positionalArgs.size() != 6){
                cout<<"usage example: " << argv[0] << " [OPTIONS] inputParentFolder minLengthOfPattern maxLengthOfPattern minNumberOfAffectedSequences outputFolder proteinGroupFolderName" << endl;
                cout << "Use --help or -h for more information." << endl;
                return 0;
    }




    // 1. Parameters
    // =============

    //f. family name
    string proteinGroupFolderName = positionalArgs[5];

    //a. inputFolder (folder with *.fasta files)
    string inputFolder = positionalArgs[0];
    inputFolder += "/" + proteinGroupFolderName + "/";

    //b. minLengthOfPattern
    unsigned long minLengthOfPattern=toUnsignedLong(positionalArgs[1].c_str());
    
    //c. maxLengthOfPattern
    unsigned long maxLengthOfPattern=toUnsignedLong(positionalArgs[2].c_str());
    
    //d. minNumberOfAffectedSequences
    unsigned long minNumberOfAffectedSequences=toUnsignedLong(positionalArgs[3].c_str());
    
    //e. output folder
    string outputFolderByFamily = positionalArgs[4]; 
    outputFolderByFamily += "/" + proteinGroupFolderName;

    // More Parameters
    // ... folder for tmp files generated by this program
    string tmpFolder = "./tmp/"; 
    // ... python script that transform seqs from *.fasta to (ABCD+AJHJHGD+...+KJHKAJSH+$) ('+' is the character separator)
    // ... requires biopython previously installed
    string multifastaConcatenateTool = "./multifastaConcatenate.py";
    // ... temporal output file name of multifastaConcatenateTool
    string tmpFastaConcatenatedFiles = tmpFolder+"_inputConcatenatedFastaFiles.txt";
    // ... tool that compute Suffix Array (SA) (uses 64 bits)
    // ... requieres gsufsort-64 previously installed
    // ... Instructions to install gsufsort-64
    // ... a. git clone https://github.com/felipelouza/gsufsort.git
    // ... b. cd gsufsort
    // ... c. make
    string gsufsortTool ="./gsufsort/gsufsort-64";
    // ... temporal output file name of SA from gsufsortTool
    string tmp_SA_File=tmpFolder+"_SA.tmp";
    
        
    // Variables
    unsigned char *T;   // concatenated seqs
    unsigned long *idT; // seq id for each letter from concatenated seqs
    unsigned long *SA;  // SA 
    unsigned int *LCP;  // LCP
    unsigned long n;    // size of T

    set<string> SMR;    // Super      Maximal Repeats
    set<string> NN;     // Non-Nested Maximal Repeats
    set<string> NE;     // Nested     Maximal Repeats
    
    
    // 0. folder creation
    system(("mkdir -p "+tmpFolder).c_str());
    system(("mkdir -p "+outputFolderByFamily).c_str());
    
    // 1. Generates inputfile T (ABCD+DJHGAJHJHGD+...+KJHKAJSHKJASH+)
    cout << "Phase 1: Fasta files Concatenation & dataset creation      -> Started! " << endl;
    system(("python3 "+multifastaConcatenateTool+" "+inputFolder+" "+tmpFastaConcatenatedFiles+" "+outputFolderByFamily).c_str());    
    cout << "Phase 1: Fasta files Concatenation                -> Finished! " << endl;

    // 2. Compute SA and n. 
    ok=compute_SA(gsufsortTool, tmpFastaConcatenatedFiles, tmp_SA_File, tmpFolder,n, SA);
    if(!ok) {
        cout << "Error: compute_SA!" << endl;
        return false;
    }
    cout << "Phase 2: Compute SA                               -> Finished! " << endl;
    
    
    // 3. Load original text (T). I did it after SA in order to have more memory for SA computation.
    ok=loadOriginalText(tmpFastaConcatenatedFiles, n, T, idT);
    cout << "Phase 3: Load in memory conatenated *.fasta files -> Finished! " << endl;
    
    // 4. Compute LCP. 
    cout << "Phase 4: Compute LCP (using " << lcpAlgorithm << " algorithm) -> Started! " << endl;
    ok=compute_LCP(n, T, SA, LCP, lcpAlgorithm);
    if(!ok) return 1;
    cout << "Phase 4: Compute LCP                              -> Finished! " << endl;
 
 
    // 5. patterns computation
    string composedPrefixName=outputFolderByFamily + "/" + proteinGroupFolderName;
;
    composedPrefixName+="_"+toString(minLengthOfPattern);
    composedPrefixName+="_"+toString(maxLengthOfPattern);
    composedPrefixName+="_"+toString(minNumberOfAffectedSequences);
    
    ok = computePatterns(composedPrefixName, n, T, idT, SA, LCP, minLengthOfPattern, maxLengthOfPattern, minNumberOfAffectedSequences);
    if(!ok) return 1;
    cout << "Phase 5: Compute patterns                         -> Finished! " << endl;

    
  
    return 0;

  
}


