#!/bin/bash

declare -a familiesDatasets=("familyDataset" "testGroupDataset")
outputFolder="output"
# change input folder pointing to parent folder that contains families datasets
inputFolder="~/tesis/proteins_db/canonicalAminoacidsProteins"

# creates output folder
mkdir -p ${outputFolder}


# generates MRs files (SMR, NN, NE) for each family in families
for f in ${familiesDatasets[@]};
do
   echo 
   echo 
   echo Procesando: ${f}
   ./mr-generator-with-statistics ${inputFolder}/$f/ 1 999999 1 ${outputFolder}/${f}
done

 



