#!/bin/bash

declare -a familiesDatasets=("controlDataset" "controlDataset_test")
outputFolder="output"
# change input folder pointing to parent folder that contains families datasets
inputFolder="~/tesis/proteins_db/canonicalAminoacidsProteins"

# generates MRs files (SMR, NN, NE) for each family in families
for f in ${familiesDatasets[@]};
do
   echo 
   echo 
   echo Procesando: ${f}
   ./mr-generator-with-statistics ${inputFolder} 1 999999 1 ${outputFolder} ${f}
done

 



